"""Aggiunto flag markdown su Post

Revision ID: 376cc6008e40
Revises: a8cdd77fa403
Create Date: 2025-03-28 08:47:39.790705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376cc6008e40'
down_revision = 'a8cdd77fa403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('cognome',
               existing_type=sa.TEXT(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=12),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=25),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=25),
               type_=sa.TEXT(length=25),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=12),
               type_=sa.TEXT(length=12),
               existing_nullable=False)
        batch_op.alter_column('cognome',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('markdown')

    # ### end Alembic commands ###
