"""Aggiunto immagine utente

Revision ID: 722be624381f
Revises: 376cc6008e40
Create Date: 2025-03-28 16:20:17.197937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722be624381f'
down_revision = '376cc6008e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
