"""empty message

Revision ID: 8f14d4a07340
Revises: b25e2b7da4b5
Create Date: 2025-03-25 19:33:03.687925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f14d4a07340'
down_revision = 'b25e2b7da4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('cognome',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cognome',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
