"""Aggiunti nome e cognome

Revision ID: 9f3b6bdea6a1
Revises: 586a1f33e153
Create Date: 2025-03-25 18:29:17.076938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3b6bdea6a1'
down_revision = '586a1f33e153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('cognome', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
