"""empty message

Revision ID: bfa4c7347f05
Revises: 9f3b6bdea6a1
Create Date: 2025-03-25 18:52:56.388518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4c7347f05'
down_revision = '9f3b6bdea6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('cognome', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cognome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
